package com.example.travelhub.domain.model

import java.time.Instant
import java.time.LocalDate

/**
 * Self-contained QR payload that's signed and embedded in the QR image.
 *
 * - [expEpochSeconds] is a UNIX timestamp; consumers should treat anything past it as invalid.
 * - The signature is generated by [com.example.travelhub.data.local.HmacQrTokenProvider]
 *   using HMAC-SHA256 over the string form of this payload.
 */
data class QrPayload(
    val reservationId: String,
    val userId: String,
    val hotelId: String,
    val confirmationCode: String,
    val issuedAtEpochSeconds: Long,
    val expEpochSeconds: Long
) {
    /** Canonical text form used for signing AND for what's embedded in the QR. */
    fun canonical(): String = listOf(
        "v1", reservationId, userId, hotelId, confirmationCode,
        issuedAtEpochSeconds.toString(), expEpochSeconds.toString()
    ).joinToString("|")
}

/**
 * The actual artifact the UI renders.
 *
 * - [token] is what gets encoded into the QR image (`canonicalPayload.signature` base64).
 * - [payload] is kept for the in-app "info" dialog (no decoding needed at render time).
 * - [availability] tells the screen what to draw (active vs grey-out vs hide).
 */
data class QrToken(
    val token: String,
    val payload: QrPayload,
    val signature: String,
    val availability: QrAvailability
)

enum class QrAvailability {
    /** The QR is within its validity window — render it active. */
    ACTIVE,
    /** Reservation already checked in — render greyed-out with a "Checked in" badge. */
    ALREADY_CHECKED_IN,
    /** Past [Booking.checkOut] — render greyed-out with "Expired". */
    EXPIRED,
    /** Reservation cancelled — render greyed-out. */
    CANCELLED
}

/**
 * Convenience: derive availability from a booking and the current instant.
 * Logic: any time on or before [Booking.checkOut] is considered "active" (per HU
 * "antes o durante la fecha de check-in", interpreted as "until checkout").
 */
fun availabilityFor(
    booking: Booking,
    now: LocalDate = LocalDate.now()
): QrAvailability = when {
    booking.isCheckedIn -> QrAvailability.ALREADY_CHECKED_IN
    booking.status == BookingStatus.CANCELLED -> QrAvailability.CANCELLED
    now.isAfter(booking.checkOut) -> QrAvailability.EXPIRED
    else -> QrAvailability.ACTIVE
}
